POST http://localhost:9000/api/v3/account/login
Content-Type: application/json

{
    "loginName": "sang2@gmail",
    "password": "123"
}

###

GET http://localhost:9000/api/v3/account/select_list?page=0&pageSize=15&search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTI3NzdiMTc4NWE2NDg1ZGJmZDZjMjMiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjMwMTUyODA0LCJleHAiOjE2MzAxNTY0MDR9.HvMFalQ2XdbCO8hjCNsYJOjQu9j1fl6IDn0yxuR4Eag


###

GET http://localhost:9000/api/v3/folder/select_list?parentId=0&page=0&pageSize=100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTIzMjA1NWQ3MzExZjM1Njk2YWIxYTQiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjI5ODk2ODA3LCJleHAiOjE2Mjk5MDA0MDd9.IWx4yyv8Dwr20K4HVT601LNScrVOW4ii_HmS3-LS3Qk

###

POST http://localhost:9000/api/v3/account/register
Content-Type: application/json

{
    "name": "Sang Tran",
    "loginName": "teonv",
    "password": "123456"
}

###

GET http://localhost:9000/api/v3/folder?page=0&pageSize=10&parentId=611a888057bd5e6599ce5090&categoryId=611a73b97a60539c85af46c6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE4ZTMxZDQ1NGU0ZGFhZjAxZWE5MDEiLCJpYXQiOjE2MjkxMjg0OTQsImV4cCI6MTYyOTEzMjA5NH0.a4PyicHgIUapKNNLDXV7Sya7RtFRFEPQw3anty2deKg

###

GET http://localhost:9000/api/v3/folder/select_list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE4ZTMxZDQ1NGU0ZGFhZjAxZWE5MDEiLCJpYXQiOjE2MjkxMjg0OTQsImV4cCI6MTYyOTEzMjA5NH0.a4PyicHgIUapKNNLDXV7Sya7RtFRFEPQw3anty2deKg

###

POST http://localhost:9000/api/v3/folder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE4ZTMxZDQ1NGU0ZGFhZjAxZWE5MDEiLCJpYXQiOjE2MjkxMjg0OTQsImV4cCI6MTYyOTEzMjA5NH0.a4PyicHgIUapKNNLDXV7Sya7RtFRFEPQw3anty2deKg

{
  "id": 0,
  "name": "folder2.3",
  "parentId": "611a888057bd5e6599ce5090",
  "categoryId": "611a73b97a60539c85af46c6"
}

###

DELETE http://localhost:9000/api/v3/folder/611a88b057bd5e6599ce5093
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE4ZTMxZDQ1NGU0ZGFhZjAxZWE5MDEiLCJpYXQiOjE2MjkxMjg0OTQsImV4cCI6MTYyOTEzMjA5NH0.a4PyicHgIUapKNNLDXV7Sya7RtFRFEPQw3anty2deKg


