POST http://localhost:9000/api/v3/login
Content-Type: application/json

{
    "loginName": "dungh",
    "password": "123456"
}

###

GET http://localhost:9000/api/v3/user/list?search=teo&page=0&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE3YjFmYzUyMTIzMzU2Y2UwMTIxODUiLCJpYXQiOjE2MjkwMzAzMDIsImV4cCI6MTYyOTAzMzkwMn0.vScQh7d1Zv4QY_VquRw_ubvjEbT0UwKMIfQEhEz-6e4


###

GET http://localhost:9000/api/v3/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE3YjFmYzUyMTIzMzU2Y2UwMTIxODUiLCJpYXQiOjE2MjkwMzAzMDIsImV4cCI6MTYyOTAzMzkwMn0.vScQh7d1Zv4QY_VquRw_ubvjEbT0UwKMIfQEhEz-6e4

###

POST http://localhost:9000/api/v3/register
Content-Type: application/json

{
    "name": "Hoang",
    "loginName": "dungh12345",
    "password": "123456"
}

###

GET http://localhost:9000/api/v3/folder?page=0&pageSize=10&parentId=611a888057bd5e6599ce5090&categoryId=611a73b97a60539c85af46c6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE4ZTMxZDQ1NGU0ZGFhZjAxZWE5MDEiLCJpYXQiOjE2MjkxMjg0OTQsImV4cCI6MTYyOTEzMjA5NH0.a4PyicHgIUapKNNLDXV7Sya7RtFRFEPQw3anty2deKg

###

GET http://localhost:9000/api/v3/folder/select_list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE4ZTMxZDQ1NGU0ZGFhZjAxZWE5MDEiLCJpYXQiOjE2MjkxMjg0OTQsImV4cCI6MTYyOTEzMjA5NH0.a4PyicHgIUapKNNLDXV7Sya7RtFRFEPQw3anty2deKg

###

POST http://localhost:9000/api/v3/folder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE4ZTMxZDQ1NGU0ZGFhZjAxZWE5MDEiLCJpYXQiOjE2MjkxMjg0OTQsImV4cCI6MTYyOTEzMjA5NH0.a4PyicHgIUapKNNLDXV7Sya7RtFRFEPQw3anty2deKg

{
  "id": 0,
  "name": "folder2.3",
  "parentId": "611a888057bd5e6599ce5090",
  "categoryId": "611a73b97a60539c85af46c6"
}

###

DELETE http://localhost:9000/api/v3/folder/611a88b057bd5e6599ce5093
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE4ZTMxZDQ1NGU0ZGFhZjAxZWE5MDEiLCJpYXQiOjE2MjkxMjg0OTQsImV4cCI6MTYyOTEzMjA5NH0.a4PyicHgIUapKNNLDXV7Sya7RtFRFEPQw3anty2deKg


